export enum FailureCode {
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  CURRENCY_MISMATCH = "CURRENCY_MISMATCH",
  INVALID_AMOUNT = "INVALID_AMOUNT",
  DUPLICATE_TRANSACTION = "DUPLICATE_TRANSACTION",
  REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND",
  INVALID_REFERENCE_KIND = "INVALID_REFERENCE_KIND",
  ALREADY_REFUNDED = "ALREADY_REFUNDED",
  ALREADY_ROLLED_BACK = "ALREADY_ROLLED_BACK",
  REFERENCE_MISMATCH = "REFERENCE_MISMATCH",
  NEGATIVE_BALANCE_REVERSAL = "NEGATIVE_BALANCE_REVERSAL",
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  IDEMPOTENCY_PAYLOAD_MISMATCH = "IDEMPOTENCY_PAYLOAD_MISMATCH",
}
