apiVersion: v1
kind: ConfigMap
metadata:
  name: wagering-processor-config
  labels:
    app: wagering-processor
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "wagering_db"
  AWS_REGION: "us-east-1"
  SQS_ENDPOINT: "http://localstack-service:4566"
