apiVersion: v1
kind: Service
metadata:
  name: wagering-processor-service
  labels:
    app: wagering-processor
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: wagering-processor
